---
- name: Set authorized key taken from file for ceph
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', 'results/{{vars_project}}_{{vars_env}}/ceph.pub') }}"
  tags: configuration

- name: Set ceph.conf to {{host2}} and {{host3}}
  copy:
    src: "results/{{vars_project}}_{{vars_env}}/ceph.conf"
    dest: /etc/ceph/ceph.conf
    owner: root
    group: root
    mode: '0644'
  tags: configuration

- name: Set ceph.client.admin.keyring to {{host2}} and {{host3}}
  copy:
    src: "results/{{vars_project}}_{{vars_env}}/ceph.client.admin.keyring"
    dest: /etc/ceph/ceph.client.admin.keyring
    owner: root
    group: root
    mode: '0600'
  tags: configuration
