---
- name: Add osd to {{vars_hosts}} 
  shell: |
    sudo ceph osd tree | column -t -s $'\t'
  become: true
  become_user: "{{vars_appuser}}"
  tags: configuration

- name: Add osd to {{vars_hosts}} 
  shell: |
    sudo ceph orch daemon add osd {{item}}:/dev/{{dev2}}
  become: true
  become_user: "{{vars_appuser}}"
  loop: "{{vars_hosts}}"
  tags: configuration
