---
- name: Create directory /etc/ssh/ssh_config.d
  file:
    path: /etc/ssh/ssh_config.d
    owner: root
    group: root
    mode: '0755'
    state: directory
  tags: requisite 

- name: Set ssh config for Ceph
  template:
    src: ssh_conf.j2
    dest: "/etc/ssh/ssh_config.d/ceph.conf"
    owner: root
    group: root
    mode: '0644'
    backup: yes
  tags: requisite

- name: Add line 1 to sysctl.conf
  lineinfile:
    path: /etc/sysctl.conf
    line: kernel.pid_max=4194303
    state: present
  tags: requisite

- name: Add line 2 to sysctl.conf
  lineinfile:
    path: /etc/sysctl.conf
    line: fs.aio-max-nr=1048576
    state: present
  tags: requisite

- name: Create directory /etc/ceph
  file:
    path: /etc/ceph
    owner: "{{vars_appuser}}"
    group: "{{vars_appuser}}"
    mode: '0755'
    state: directory
  tags: requisite 
