---
- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
  tags: prerequisite

- name: Install LVM2
  yum:
    name: lvm2.x86_64
    state: present
  tags: prerequisite

- name: Install NFS
  yum:
    name: nfs-utils.x86_64
    state: present
  tags: prerequisite