---
- name: Create directory for mount nfs dir
  file:
    path: "{{nfs_dir}}"
    owner: root
    group: root
    state: directory
  register: dir_created
  tags: prerequisite 
   
- name: Edit fstab and mount the NFS volume
  mount:
    name: "{{nfs_dir}}"
    src: 10.206.210.243:/nfs
    fstype: nfs4
    opts: "noatime"
    state: mounted
  when: dir_created is succeeded
  register: mounted
  tags: prerequisite