---
- name: Create file exports
  copy:
    dest: /etc/exports
    content: |
      /nfs  10.206.210.237(rw,sync,no_root_squash,no_all_squash)
      /nfs  10.206.210.249(rw,sync,no_root_squash,no_all_squash)
      /nfs  10.206.210.236(rw,sync,no_root_squash,no_all_squash)
    owner: root
    group: root
    mode: '0600'
    backup: yes